### PR TITLE
T293 docker

### PR DESCRIPTION
**Pull request by justinlittman**
For #293

### CODE REVIEW

**Comment by anksharm** [comment]
-- The Readme needs instruction to setup /edit cronjob for app-dev env.
-- Instructions for /admin page changes, should be followed up after the docker-setup.

**Comment by justinlittman** [comment]
@anksharm Can you remind me what your second suggestion above means?  Thanks.

**Comment by kerchner** [comment]
@justinlittman as discussed, even though the merge button is green, this branch can probably use a rebase first.

**Comment by kerchner** [comment]
@justinlittman also, please git squash this branch.

**Comment by kerchner** [comment]
Reassigning to @rajatvij to test as well

**Comment by rajatvij** [comment]
Additional Notes in Readme can have one more section for Usage to have more clarity, which should contain following:
-- SFM Admin account details
-- How to run management commands

And Expand links doesn't work in case of Retweets having more than 140 characters, but that can be a totally unrelated issue.

**Comment by kerchner** [comment]
Assigning back to self to rebase and squash before merge

**Pull request merged**
