### PR TITLE
T258 filterstream boolean chk

### PR DESCRIPTION
**Pull request by anksharm**

### CODE REVIEW

**Comment by anksharm** [comment]
Words field in TwitterFilter : spaces and comma should have a AND/OR logic. 
people: Api now fetches using uids instead of screen_names.
locations:  use float value of locations

Filterstream change:
-- words to handle AND-OR logic
-- uids to be sent to api instead of screen_names for people
-- locations -- float value been used in APi call

Migrations file:
-- uids column added
-- change to include a comma for every space in words for existing filters.
-- change to fetch uids for existing accounts
-- change to log invalid account(uids not fetched) in log/output file.

Models file:
-- new column uids in TwitterFilter
-- change in "help-text" under each field in TwitterFilter form
-- clean() change to handle expressions in Words,people and locations

admin.py 
-- override for default save() method, using save_model()
-- bulk fetch of uids for people.
-- warning messages per invalid accounts and TweepyError

Docs
-- each field explained
-- TwitterFilter snapshot

**Comment by kerchner** [comment]
@anksharm A few observations:
The migration script seems to work well.  When it comma-separates the Words and People terms, it separates with just a comma ("a,b,c"), not comma-space ("a, b, c").  However, when the user re-saves the TwitterFilter, comma-separated terms are separated with comma-space in People, but not in Words.   Excess spaces are cleaned up in People, but not in Words.  Line feeds are eliminated from both Words and People.

Please eliminate excess spaces (i.e. more than 1 at a time) from Words.   It would be nice if the migration script comma-space-separated the People and Words terms.

To consider:  For terms that are just comma-separated in Words (like "a,b,c") do we want to comma-space separate them ("a, b, c")?

**Comment by kerchner** [comment]
@anksharm, TwitterFilters break with this branch.

Here is where I believe the problem is:  Assuming you upgrade tweepy to 3.2.0 (which was brought in when the branch was rebased w/master).  In this branch, the code in filterstream.py passes a list of uids to ```tweepy.Stream.filter``` (at https://github.com/gwu-libraries/social-feed-manager/blob/t258-filterstream-boolean-chk/sfm/ui/management/commands/filterstream.py#L115 ).  The error being passed back from tweepy indicates that tweepy is trying to ```.join``` together a list of ```int```s, which python doesn't let you do.  Basically tweepy 3.2.0 seems to be expecting a list of Strings, not ints, and I assume (<-- untested assumption) based on the Twitter API documentation that tweepy expects a list of string-ified uids.

While you're in there, you can also add uids to the list of filter properties you print out when in --verbose mode.

Please ensure that you've tested various types of twitterfilters (with/without Words, with/without People, Locations, etc.) with tweepy 3.2.0 installed, and that the stream data still looks correct.

**Comment by anksharm** [comment]
@kerchner pushed the changes. fingers-crossed :+1:

**Comment by kerchner** [comment]
- Remove the link to the API documentation for People, as discussed.  We decided to do this because the Twitter API ```follow``` parameter takes numeric uids, but SFM takes Twitter account names and on the back end, translates these to uids as a convenience for the user.
- Locations.  We realized that the API can accept a list of bounding boxes, e.g. -122.75,36.8,-121.75,37.8,-74,40,-73,41 for San Francisco OR NYC.  SFM should accept a valid list of bounding boxes.  If the user entered anything other than a valid list of bounding boxes, the message should simply say "Please enter a valid list of bounding boxes."
- Update documentation to reflect the above.  @kerchner to make appropriate notes in the release notes #323 as well.

**Comment by anksharm** [comment]
@kerchner 
* no change required in filterstream to handle list of bounding boxes. Works good :+1: 
* I hope migration should work all good now

**Comment by kerchner** [comment]
@anksharm migration seems to work, but Locations currently allows for a value like "1,1,1,1,0" which is not a valid set of bounding boxes.  I just checked in some changes to check only that:
- The # of values is divisible by 4
- Each value is between -180 and +180
Also cleaned up some of the messaging in the migration script as well as the clean() validation messages.

**Comment by anksharm** [comment]
This was allowed , in case for the user to add a list of bounding boxes.
The user should add a valid set of bounding boxes

On Sunday, March 15, 2015, Dan Kerchner <notifications@github.com> wrote:

> @anksharm <https://github.com/anksharm> migration seems to work, but
> Locations currently allows for a value like "1,1,1,1,0" which is not a
> valid set of bounding boxes. I just checked in some changes to check only
> that:
>
>    - The # of values is divisible by 4
>    - Each value is between -180 and +180 Also cleaned up some of the
>    messaging in the migration script as well as the clean() validation
>    messages.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gwu-libraries/social-feed-manager/pull/279#issuecomment-81181657>
> .
>


-- 
Sent from Gmail Mobile

**Comment by kerchner** [comment]
Not sure that I understand.  A bounding box consists of 4 values.  So a valid list of bounding boxes would consist of 4, 8, 12, etc. values.

**Pull request merged**
