### PR TITLE
T260 fetch tweets by

### PR DESCRIPTION
**Pull request by justinlittman**

### CODE REVIEW

**Comment by kerchner** [comment]
@justinlittman  - I pulled this branch and attempted to pip install the updated requirements (i.e. the updated tweepy package).  I got the following error (but keep reading past):

```
Downloading/unpacking tweepy>=3.1.0 (from -r requirements.txt (line 8))
  Downloading tweepy-3.2.0.tar.gz
  Running setup.py egg_info for package tweepy
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/home/kerchner/projects/social-feed-manager/ENV/build/tweepy/setup.py", line 17, in <module>
        install_reqs = parse_requirements('requirements.txt', session=uuid.uuid1())
    TypeError: parse_requirements() got an unexpected keyword argument 'session'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/home/kerchner/projects/social-feed-manager/ENV/build/tweepy/setup.py", line 17, in <module>

    install_reqs = parse_requirements('requirements.txt', session=uuid.uuid1())

TypeError: parse_requirements() got an unexpected keyword argument 'session'
```

Also tried pip uninstalling tweepy, and re- pip installing requirements.txt.

I had the ubuntu package version of pip running, so (based on some reading online) I upgraded my version of pip (```sudo pip install -U pip```) - first locally within the virtualenv, then globally (hey, why not).  This resolved it.

Did you have to do this in order to install tweepy 3.1.0?

I'm not sure we have a choice if we're going to require tweepy 3.1.0 .  But I'll put this out there for your comment before proceeding.

**Comment by kerchner** [comment]
pip version before upgrade was:
```pip 1.0 from /usr/lib/python2.7/dist-packages (python 2.7)```
after upgrade is:
```pip 6.0.7 from /usr/local/lib/python2.7/dist-packages (python 2.7)```
(or if upgrading just within the virtualenv:  ```pip 6.0.7 from /home/kerchner/projects/social-feed-manager/ENV/local/lib/python2.7/site-packages``` )

And I have a feeling that part of the broader answer to this might involve the word "docker" ...

**Comment by justinlittman** [comment]
I know that when I build the docker images I upgrade pip (but I forget what motivated that step).

**Comment by edsu** [comment]
Awesome! :cake:

**Pull request merged**
