### PR TITLE
Bumps tweepy to 3.4.0. Fixes #316.

### LINKED ISSUE #316: filterstream process stops writing
I changed the `SAVE_INTERVAL_SECONDS` to be 86400 (24 hours) so that my `DATA_DIR` wouldn't need to be cleaned up so often. Things appeared to work for three days but then the filterstream processes stopped writing to `DATA_DIR`.  The filterstream management commands were running, but appeared to be consuming a lot of CPU.

Has anyone else noticed behavior like this?  Was SAVE_INTERVAL_SECONDS set to 15 minutes to avoid something like this happening? 

I didn't see anything unusual in my supervisor.log, just that the processes started up ok:

```
2015-02-20 02:31:25,221 INFO success: twitterfilter-2 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2015-02-20 02:31:25,221 INFO success: twitterfilter-1 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2015-02-20 02:31:25,221 INFO success: twitterfilter-4 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2015-02-20 10:28:15,417 INFO spawned: 'twitterfilter-5' with pid 30045
2015-02-20 10:28:16,424 INFO success: twitterfilter-5 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

Any advice/tips you could provide would be appreciated. FWIW, the twitterfilter-5 filterstream was archiving about 300k tweets per day, for three days before all the filterstreams went into limbo.

### PR DESCRIPTION
**Pull request by kerchner**

### CODE REVIEW

**Comment by rajatvij** [comment]
@kerchner To test this do i need to change the supervisor interval or would the default interval be okay?

**Comment by kerchner** [comment]
Doesn't matter but it would be faster for you if you shorten the interval :)

**Comment by rajatvij** [comment]
@kerchner I ran a twitter filter with an interval of 5 minutes from 11:27 to 14:32 today. I haven't run into any issues yet. I checked and it seems its only taking 1% of CPU and 2.3% memory on my system. Which looks fine too.
I am not sure if this much test is enough, so if this looks good to you, we can merge and close the ticket.

**Comment by kerchner** [comment]
@rajatvij yes please merge

**Pull request merged**
